[project]
name = "espn-nfl-scraper"
version = "0.1.0"
description = "A scraper for ESPN NFL data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "scrapegraphai>=1.52.0",
]
